<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class KegiatanFactory extends Factory
{
    protected static $keg = [
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.2.01' , 'nama' => 'Pengelolaan Pendidikan Sekolah Dasar' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.2.02' , 'nama' => 'Pengelolaan Pendidikan Sekolah Menengah Pertama' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.2.03' , 'nama' => 'Pengelolaan Pendidikan Anak Usia Dini (PAUD)' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.2.04' , 'nama' => 'Pengelolaan Pendidikan Nonformal/Kesetaraan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.3.05' , 'nama' => 'Pengelolaan Pendidikan Sekolah Menengah Atas' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.3.06' , 'nama' => 'Pengelolaan Pendidikan Sekolah Menengah Kejuruan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.02.3.07' , 'nama' => 'Penyediaan Pendidikan layanan khusus bagi OAP' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.03.3.02' , 'nama' => 'Penetapan Kurikulum Muatan Lokal Pendidikan Anak Usia Dini dan Pendidikan Non Formal' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.04.2.01' , 'nama' => 'Pemerataan Kuantitas dan Kualitas Pendidik dan Tenaga Kependidikan bagi Satuan Pendidikan Dasar, PAUD, dan Pendidikan Nonformal/Kesetaraan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.01.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.02.2.01' , 'nama' => 'Penyediaan Fasilitas Pelayanan Kesehatan untuk UKM dan UKP Kewenangan Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.02.2.02' , 'nama' => 'Penyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.02.2.03' , 'nama' => 'Penyelenggaraan Sistem Informasi Kesehatan Secara Terintegrasi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.02.2.04' , 'nama' => 'Penerbitan Izin Rumah Sakit Kelas C, D dan Fasilitas Pelayanan Kesehatan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.02.3.02' , 'nama' => 'Penyediaan Layanan Kesehatan untuk UKM dan UKP Rujukan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.03.2.02' , 'nama' => 'Perencanaan Kebutuhan dan Pendayagunaan Sumber Daya Manusia Kesehatan untuk UKP dan UKM di Wilayah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.03.2.03' , 'nama' => 'Pengembangan Mutu dan Peningkatan Kompetensi Teknis Sumber Daya Manusia Kesehatan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.05.2.03' , 'nama' => 'Pengembangan dan Pelaksanaan Upaya Kesehatan Bersumber Daya Masyarakat (UKBM) Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.02.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.02.2.01' , 'nama' => 'Pengelolaan SDA dan Bangunan Pengaman Pantai pada Wilayah Sungai (WS) dalam 1 (Satu) Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.03.2.01' , 'nama' => 'Pengelolaan dan Pengembangan Sistem Penyediaan Air Minum (SPAM) di Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.04.2.01' , 'nama' => 'Pengembangan Sistem dan Pengelolaan Persampahan di Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.06.2.01' , 'nama' => 'Pengelolaan dan Pengembangan Sistem Drainase yang Terhubung Langsung dengan Sungai dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.09.2.01' , 'nama' => 'Penyelenggaraan Penataan Bangunan dan Lingkungannya di Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.10.2.01' , 'nama' => 'Penyelenggaraan Jalan Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.03.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.02.2.07' , 'nama' => 'Penerbitan Sertifikat Kepemilikan Bangunan Gedung (SKGB)' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.03.2.02' , 'nama' => 'Penataan dan Peningkatan Kualitas Kawasan Permukiman Kumuh dengan Luas di Bawah 10 (Sepuluh) Ha' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.03.2.03' , 'nama' => 'Peningkatan Kualitas Kawasan Permukiman Kumuh dengan Luas di Bawah 10 (Sepuluh) Ha' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.04.2.01' , 'nama' => 'Pencegahan Perumahan dan Kawasan Permukiman Kumuh pada Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.05.2.01' , 'nama' => 'Urusan Penyelenggaraan PSU Perumahan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.04.2.01' , 'nama' => 'Pencegahan, Pengendalian, Pemadaman, Penyelamatan, dan Penanganan Bahan Berbahaya dan Beracun Kebakaran dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.04.2.04' , 'nama' => 'Pemberdayaan Masyarakat dalam Pencegahan Kebakaran' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.03.2.02' , 'nama' => 'Pelayanan Pencegahan dan Kesiapsiagaan Terhadap Bencana' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.05.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.02.2.01' , 'nama' => 'Pemberdayaan Sosial Komunitas Adat Terpencil (KAT)' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.02.3.03' , 'nama' => 'Pengembangan Potensi Sumber Kesejahteraan Sosial Daerah di Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.02.3.05' , 'nama' => 'Pendataan Lembaga Kesejahteraan Sosial Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.04.2.01' , 'nama' => 'Rehabilitasi Sosial Dasar Penyandang Disabilitas Terlantar, Anak Terlantar, Lanjut Usia Terlantar, serta Gelandangan Pengemis di Luar Panti Sosial' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.04.2.02' , 'nama' => 'Rehabilitasi Sosial Penyandang Masalah Kesejahteraan Sosial (PMKS) Lainnya Bukan Korban HIV/AIDS dan NAPZA di Luar Panti Sosial' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.05.2.01' , 'nama' => 'Pemeliharaan Anak-Anak Terlantar' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.05.2.02' , 'nama' => 'Pengelolaan Data Fakir Miskin Cakupan Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.06.2.01' , 'nama' => 'Perlindungan Sosial Korban Bencana Alam dan Sosial Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.06.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.03.2.01' , 'nama' => 'Pelaksanaan Pelatihan berdasarkan Unit Kompetensi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.03.2.02' , 'nama' => 'Pembinaan Lembaga Pelatihan Kerja Swasta' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.04.2.01' , 'nama' => 'Pelayanan antar Kerja di Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.07.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.03.2.01' , 'nama' => 'Pemeriksaan dan Pengawasan Koperasi, Koperasi Simpan Pinjam/Unit Simpan Pinjam Koperasi yang Wilayah Keanggotaannya dalam Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.05.2.01' , 'nama' => 'Pendidikan dan Latihan Perkoperasian Bagi Koperasi yang Wilayah Keanggotaan dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.06.2.01' , 'nama' => 'Pemberdayaan dan Perlindungan Koperasi yang Keanggotaannya dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.06.3.01' , 'nama' => 'Pemberdayaan dan Perlindungan Koperasi yang Keanggotaannya dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.07.2.01' , 'nama' => 'Pemberdayaan Usaha Mikro yang Dilakukan Melalui Pendataan, Kemitraan, Kemudahan Perizinan, Penguatan Kelembagaan dan Koordinasi dengan Para Pemangku Kepentingan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.08.2.01' , 'nama' => 'Pengembangan Usaha Mikro dengan Orientasi Peningkatan Skala Usaha Menjadi Usaha Kecil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.17.09.3.01' , 'nama' => 'Pemberian pendampingan dan penyuluhan pendirian koperasi.' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.02.2.03' , 'nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Pemberdayaan Perempuan Kewenangan Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.03.2.02' , 'nama' => 'Penyediaan Layanan Rujukan Lanjutan bagi Perempuan Korban Kekerasan yang Memerlukan Koordinasi Kewenangan Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.04.2.01' , 'nama' => 'Peningkatan Kualitas Keluarga dalam Mewujudkan Kesetaraan Gender (KG) dan Hak Anak Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.05.2.01' , 'nama' => 'Pengumpulan, Pengolahan Analisis dan Penyajian Data Gender dan Anak Dalam Kelembagaan Data di Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.06.2.02' , 'nama' => 'Penguatan dan Pengembangan Lembaga Penyedia Layanan Peningkatan Kualitas Hidup Anak Kewenangan Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.08.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.02.2.02' , 'nama' => 'Pemetaan Perkiraan Pengendalian Penduduk Cakupan Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.03.2.01' , 'nama' => 'Pelaksanaan Advokasi, Komunikasi, Informasi dan Edukasi (KIE) Pengendalian Penduduk dan KB Sesuai Kearifan Budaya Lokal' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.03.2.02' , 'nama' => 'Pendayagunaan Tenaga Penyuluh KB/Petugas Lapangan KB (PKB/PLKB)' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.03.2.03' , 'nama' => 'Pengendalian dan Pendistribusian Kebutuhan Alat dan Obat Kontrasepsi serta Pelaksanaan Pelayanan KB di Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.03.2.04' , 'nama' => 'Pemberdayaan dan Peningkatan Peran Serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/Kota dalam Pelaksanaan Pelayanan dan Pembinaan Kesertaan Ber-KB' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.04.2.01' , 'nama' => 'Pelaksanaan Pembangunan Keluarga Melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.14.04.2.02' , 'nama' => 'Pelaksanaan dan Peningkatan Peran Serta Organisasi Kemasyarakatan Tingkat Daerah Kabupaten/ Kota dalam Pembangunan Keluarga Melalui Pembinaan Ketahanan dan Kesejahteraan Keluarga' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.03.2.01' , 'nama' => 'Pencegahan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.04.2.01' , 'nama' => 'Pengelolaan Keanekaragaman Hayati Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.08.2.01' , 'nama' => 'Penyelenggaraan Pendidikan, Pelatihan, dan Penyuluhan Lingkungan Hidup untuk Lembaga Kemasyarakatan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.11.2.01' , 'nama' => 'Pengelolaan Sampah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.11.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.02.2.01' , 'nama' => 'Pelayanan Pendaftaran Penduduk' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.03.2.02' , 'nama' => 'Penyelenggaraan Pencatatan Sipil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.03.2.03' , 'nama' => 'Pembinaan dan Pengawasan Penyelenggaraan Pencatatan Sipil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.04.2.04' , 'nama' => 'Pembinaan dan Pengawasan Pengelolaan Informasi Administrasi Kependudukan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.12.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.02.2.01' , 'nama' => 'Penyelenggaraan Penataan Desa' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.04.2.01' , 'nama' => 'Pembinaan dan Pengawasan Penyelenggaraan Administrasi Pemerintahan Desa' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.05.2.01' , 'nama' => 'Pemberdayaan Lembaga Kemasyarakatan yang Bergerak di Bidang Pemberdayaan Desa dan Lembaga Adat Tingkat Daerah Kabupaten/Kota serta Pemberdayaan Masyarakat Hukum Adat yang Masyarakat Pelakunya Hukum Adat yang Sama dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.06.3.02' , 'nama' => 'Pemberdayaan Masyarakat Kampung dalam Satu Wilayah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.13.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.02.2.02' , 'nama' => 'Penyediaan Perlengkapan Jalan di Jalan Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.02.2.09' , 'nama' => 'Penyediaan Angkutan Umum untuk Jasa Angkutan Orang dan/atau Barang Antar Kota dalam 1 (Satu) Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.03.2.12' , 'nama' => 'Pembangunan, Penerbitan Izin Pembangunan dan Pengoperasian Pelabuhan Pengumpan Lokal' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.01.2.07' , 'nama' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.15.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.02.2.01' , 'nama' => 'Pengelolaan Informasi dan Komunikasi Publik Pemerintah Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.03.2.02' , 'nama' => 'Pengelolaan E-government di Lingkup Pemerintah Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.16.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.20.02.2.01' , 'nama' => 'Penyelenggaraan Statistik Sektoral di Lingkup Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.21.02.2.01' , 'nama' => 'Penyelenggaraan Persandian untuk Pengamanan Informasi Pemerintah Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.04.2.01' , 'nama' => 'Pelayanan Perizinan dan Non Perizinan Secara Terpadu Satu Pintu dibidang Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.05.2.01' , 'nama' => 'Pengendalian Pelaksanaan Penanaman Modal yang Menjadi Kewenangan Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.18.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.02.2.01' , 'nama' => 'Penyadaran, Pemberdayaan, dan Pengembangan Pemuda dan Kepemudaan Terhadap Pemuda Pelopor Kabupaten/Kota, Wirausaha Muda Pemula, dan Pemuda Kader Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.02.2.02' , 'nama' => 'Pemberdayaan dan Pengembangan Organisasi Kepemudaan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.03.2.01' , 'nama' => 'Pembinaan dan Pengembangan Olahraga Pendidikan pada Jenjang Pendidikan yang Menjadi Kewenangan Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.03.2.02' , 'nama' => 'Penyelenggaraan Kejuaraan Olahraga Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.03.2.03' , 'nama' => 'Pembinaan dan Pengembangan Olahraga Prestasi Tingkat Daerah Provinsi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.03.2.04' , 'nama' => 'Pembinaan dan Pengembangan Organisasi Olahraga' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.19.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.02.2.01' , 'nama' => 'Pengelolaan Kebudayaan yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.02.2.02' , 'nama' => 'Pelestarian Kesenian Tradisional yang Masyarakat Pelakunya dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.22.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.02.2.01' , 'nama' => 'Pengelolaan Daya Tarik Wisata Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.02.2.02' , 'nama' => 'Pengelolaan Kawasan Strategis Pariwisata Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.02.2.03' , 'nama' => 'Pengelolaan Destinasi Pariwisata Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.03.2.01' , 'nama' => 'Pemasaran Pariwisata Dalam dan Luar Negeri Daya Tarik, Destinasi dan Kawasan Strategis Pariwisata Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.05.2.01' , 'nama' => 'Pelaksanaan Peningkatan Kapasitas Sumber Daya Manusia Pariwisata dan Ekonomi Kreatif Tingkat Dasar' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.26.05.2.02' , 'nama' => 'Pengembangan Kapasitas Pelaku Ekonomi Kreatif' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.02.2.01' , 'nama' => 'Pengelolaan Perpustakaan Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.02.2.02' , 'nama' => 'Pembudayaan Gemar Membaca Tingkat Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.23.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '2.24.02.2.01' , 'nama' => 'Pengelolaan Arsip Dinamis Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.03.2.01' , 'nama' => 'Pengelolaan Penangkapan Ikan di Wilayah Sungai, Danau, Waduk, Rawa, dan Genangan Air Lainnya yang Dapat Diusahakan dalam 1 (Satu) Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.03.2.02' , 'nama' => 'Pemberdayaan Nelayan Kecil dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.03.3.02' , 'nama' => 'Pemberdayaan Nelayan Kecil dalam Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.04.2.01' , 'nama' => 'Penerbitan Izin Usaha Perikanan di Bidang Pembudidayaan Ikan yang Usahanya dalam 1 (Satu) Daerah Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.04.2.02' , 'nama' => 'Pemberdayaan Pembudi Daya Ikan Kecil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.04.2.04' , 'nama' => 'Pengelolaan Pembudidayaan Ikan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.06.2.01' , 'nama' => 'Penerbitan Tanda Daftar Usaha Pengolahan Hasil Perikanan bagi Usaha Skala Mikro dan Kecil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.06.2.02' , 'nama' => 'Pembinaan Mutu dan Keamanan Hasil Perikanan bagi Usaha Pengolahan dan Pemasaran Skala Mikro dan Kecil' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.06.2.03' , 'nama' => 'Penyediaan dan Penyaluran Bahan Baku Industri Pengolahan Ikan dalam 1 (Satu) Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.25.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.02.2.01' , 'nama' => 'Pengawasan Penggunaan Sarana Pertanian' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.02.2.06' , 'nama' => 'Penyediaan Benih/Bibit Ternak dan Hijauan Pakan Ternak yang Sumbernya dalam 1 (Satu) Daerah Kabupaten/Kota Lain' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.03.2.01' , 'nama' => 'Pengembangan Prasarana Pertanian' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.03.2.02' , 'nama' => 'Pembangunan Prasarana Pertanian' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.05.2.01' , 'nama' => 'Pengendalian dan Penanggulangan Bencana Pertanian Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.07.2.01' , 'nama' => 'Pelaksanaan Penyuluhan Pertanian' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.27.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '1.04.05.3.01' , 'nama' => 'Urusan Penyelenggaraan PSU Perumahan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.02.2.06' , 'nama' => 'Pengendalian Fasilitas Penyimpanan Bahan Berbahaya dan Pengawasan Distribusi, Pengemasan dan Pelabelan Bahan Berbahaya di Tingkat Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.03.2.01' , 'nama' => 'Pembangunan dan Pengelolaan Sarana Distribusi Perdagangan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.03.2.02' , 'nama' => 'Pembinaan Terhadap Pengelola Sarana Distribusi Perdagangan Masyarakat di Wilayah Kerjanya' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.04.2.01' , 'nama' => 'Menjamin Ketersediaan Barang Kebutuhan Pokok dan Barang Penting di Tingkat Daerah Kabupaten/ Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.04.2.02' , 'nama' => 'Pengendalian Harga, dan Stok Barang Kebutuhan Pokok dan Barang Penting di Tingkat Pasar Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.06.2.01' , 'nama' => 'Pelaksanaan Metrologi Legal, Berupa Tera, Tera Ulang, dan Pengawasan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.30.07.2.01' , 'nama' => 'Pelaksanaan Promosi, Pemasaran dan Peningkatan Penggunaan Produk Dalam Negeri' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.02.2.01' , 'nama' => 'Penyusunan dan Evaluasi Rencana Pembangunan Industri Kabupaten/Kota' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.02.3.01' , 'nama' => 'Penyusunan, Penerapan, dan Evaluasi Rencana Pembangunan Industri Provinsi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.01.2.03' , 'nama' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '3.31.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.03' , 'nama' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.07' , 'nama' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.11' , 'nama' => 'Administrasi Keuangan dan Operasional Kepala Daerah dan Wakil Kepala Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.12' , 'nama' => 'Fasilitasi Kerumahtanggaan Sekretariat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.13' , 'nama' => 'Penataan Organisasi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.01.2.14' , 'nama' => 'Pelaksanaan Protokol dan Komunikasi Pimpinan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.02.2.01' , 'nama' => 'Administrasi Tata Pemerintahan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '8.01.03.2.01' , 'nama' => 'Perumusan Kebijakan Teknis dan Pemantapan Pelaksanaan Bidang Pendidikan Politik, Etika Budaya Politik, Peningkatan Demokrasi, Fasilitasi Kelembagaan Pemerintahan, Perwakilan dan Partai Politik, Pemilihan Umum/Pemilihan Umum Kepala Daerah, serta Pemantauan Situasi Politik' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.03.2.01' , 'nama' => 'Pelaksanaan Kebijakan Perekonomian' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.02.2.02' , 'nama' => 'Pelaksanaan Kebijakan Kesejahteraan Rakyat' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.01.03.2.03' , 'nama' => 'Pengelolaan Pengadaan Barang dan Jasa' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.02.2.02' , 'nama' => 'Pembahasan Kebijakan Anggaran' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.02.2.05' , 'nama' => 'Penyerapan dan Penghimpunan Aspirasi Masyarakat' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.02.2.08' , 'nama' => 'Fasilitasi Tugas DPRD' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.15' , 'nama' => 'Layanan Keuangan dan Kesejahteraan DPRD' ],
[ 'tahun' => 2024 , 'id_keg' =>  '4.02.01.2.16' , 'nama' => 'Layanan Administrasi DPRD' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.02.2.01' , 'nama' => 'Penyusunan Perencanaan dan Pendanaan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.02.2.02' , 'nama' => 'Analisis Data dan Informasi Pemerintahan Daerah Bidang Perencanaan Pembangunan Daerah ' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.02.2.03' , 'nama' => 'Pengendalian, Evaluasi dan Pelaporan Bidang Perencanaan Pembangunan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.02.2.04' , 'nama' => 'Implementasi Sistem Informasi Pemerintahan Daerah di Bidang Pembangunan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.03.2.01' , 'nama' => 'Koordinasi Perencanaan Bidang Pemerintahan dan Pembangunan Manusia' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.03.2.02' , 'nama' => 'Koordinasi Perencanaan Bidang Perekonomian dan SDA (Sumber Daya Alam)' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.03.2.03' , 'nama' => 'Koordinasi Perencanaan Bidang Infrastruktur dan Kewilayahan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.01.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.03.2.01' , 'nama' => 'Pengelolaan Barang Milik Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.05.02.2.01' , 'nama' => 'Penelitian dan Pengembangan Bidang Penyelenggaraan Pemerintahan dan Pengkajian Peraturan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.04.2.01' , 'nama' => 'Kegiatan Pengelolaan Pendapatan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.02.2.01' , 'nama' => 'Koordinasi dan Penyusunan Rencana Anggaran Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.02.2.02' , 'nama' => 'Koordinasi dan Pengelolaan Perbendaharaan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.02.2.03' , 'nama' => 'Koordinasi dan Pelaksanaan Akuntansi dan Pelaporan Keuangan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.02.2.04' , 'nama' => 'Penunjang Urusan Kewenangan Pengelolaan Keuangan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.02.2.05' , 'nama' => 'Pengelolaan Data dan Implementasi Sistem Informasi Pemerintah Daerah Lingkup Keuangan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.03' , 'nama' => 'Administrasi Barang Milik Daerah pada Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.02.01.2.07' , 'nama' => 'Pengadaan Barang Milik Daerah Penunjang Urusan Pemerintah Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.05.02.2.03' , 'nama' => 'Penelitian dan Pengembangan Bidang Ekonomi dan Pembangunan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.02.2.01' , 'nama' => 'Pengadaan, Pemberhentian dan Informasi Kepegawaian ASN' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.02.2.02' , 'nama' => 'Mutasi dan Promosi ASN' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.02.2.03' , 'nama' => 'Pengembangan Kompetensi ASN' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.03.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '5.04.02.2.02' , 'nama' => 'Sertifikasi, Kelembagaan, Pengembangan Kompetensi Manajerial dan Fungsional' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.02.2.01' , 'nama' => 'Penyelenggaraan Pengawasan Internal' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.02.2.02' , 'nama' => 'Penyelenggaraan Pengawasan dengan Tujuan Tertentu' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.03.2.01' , 'nama' => 'Perumusan Kebijakan Teknis di Bidang Pengawasan dan Fasilitasi Pengawasan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.03.2.02' , 'nama' => 'Pendampingan dan Asistensi' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.05' , 'nama' => 'Administrasi Kepegawaian Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '6.01.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.02.2.02' , 'nama' => 'Penyelenggaraan Urusan Pemerintahan yang Tidak Dilaksanakan oleh Unit Kerja Perangkat Daerah yang Ada di Kecamatan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.03.2.06' , 'nama' => 'Pemberdayaan dan Kesejahteraan Keluarga Tingkat Kecamatan dan Kelurahan' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.06.2.01' , 'nama' => 'Fasilitasi, Rekomendasi dan Koordinasi Pembinaan dan Pengawasan Pemerintahan Desa' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.01.2.01' , 'nama' => 'Perencanaan, Penganggaran, dan Evaluasi Kinerja Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.01.2.02' , 'nama' => 'Administrasi Keuangan Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.01.2.06' , 'nama' => 'Administrasi Umum Perangkat Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.01.2.08' , 'nama' => 'Penyediaan Jasa Penunjang Urusan Pemerintahan Daerah' ],
[ 'tahun' => 2024 , 'id_keg' =>  '7.01.01.2.09' , 'nama' => 'Pemeliharaan Barang Milik Daerah Penunjang Urusan Pemerintahan Daerah' ],
    ];
    public function definition(): array
    {
        return [];
    }

    public function predefinedData(): array
    {
        return static::$keg;
    }
}
